# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0"
